# Rocky/RHEL uses the upstream package that Fedora maintains.
name: FIO-Rocky-Build
on:
  workflow_call:
    outputs:
      # Obviously need different outputs here
      fio_pkg_debug_filename:
        description: "Filename for the FIO debug RPM package."
        value: ${{ jobs.build.outputs.fio_pkg_debug_filename }}
      fio_pkg_debug_artifact_id:
        description: "GHA Artifact ID for FIO debug RPM package."
        value: ${{ jobs.build.outputs.fio_pkg_debug_artifact_id }}
      fio_pkg_debug_source_filename:
        description: "Filename for the FIO debug source RPM package."
        value: ${{ jobs.build.outputs.fio_pkg_debug_source_filename }}
      fio_pkg_debug_source_artifact_id:
        description: "GHA Artifact ID for FIO debug source RPM package."
        value: ${{ jobs.build.outputs.fio_pkg_debug_source_artifact_id }}
      fio_pkg_hipfile_engine_filename:
        description: "Filename for the FIO hipFile IO engine RPM package."
        value: ${{ jobs.build.outputs.fio_pkg_hipfile_engine_filename }}
      fio_pkg_hipfile_engine_artifact_id:
        description: "GHA Artifact ID for FIO hipFile IO engine RPM package."
        value: ${{ jobs.build.outputs.fio_pkg_hipfile_engine_artifact_id }}
      fio_pkg_filename:
        description: "Filename for the FIO runtime RPM package."
        value: ${{ jobs.build.outputs.fio_pkg_filename }}
      fio_pkg_artifact_id:
        description: "GHA Artifact ID for FIO runtime RPM package."
        value: ${{ jobs.build.outputs.fio_pkg_artifact_id }}
      fio_pkg_source_filename:
        description: "Filename for the FIO source RPM package."
        value: ${{ jobs.build.outputs.fio_pkg_source_filename }}
      fio_pkg_source_artifact_id:
        description: "GHA Artifact ID for FIO source RPM package."
        value: ${{ jobs.build.outputs.fio_pkg_source_artifact_id }}
permissions:
  contents: read
  packages: read
jobs:
  build:
    runs-on: [ubuntu-24.04]
    container:
      image: ghcr.io/rocm/fio/fio_build_rocky:latest
      env:
        RHEL_MAJOR_VERSION: 9
    defaults:
      run:
        shell: bash
    outputs:
      fio_pkg_debug_filename: ${{ steps.pkg-metadata.outputs.FIO_PKG_DEBUG_FILENAME }}
      fio_pkg_debug_artifact_id: ${{ steps.artifact-debug.outputs.artifact-id }}
      fio_pkg_debug_source_filename: ${{ steps.pkg-metadata.outputs.FIO_PKG_DEBUG_SOURCE_FILENAME }}
      fio_pkg_debug_source_artifact_id: ${{ steps.artifact-debug-source.outputs.artifact-id }}
      fio_pkg_hipfile_engine_filename: ${{ steps.pkg-metadata.outputs.FIO_PKG_HIPFILE_ENGINE_FILENAME }}
      fio_pkg_hipfile_engine_artifact_id: ${{ steps.artifact-hipfile-engine.outputs.artifact-id }}
      fio_pkg_filename: ${{ steps.pkg-metadata.outputs.FIO_PKG_FILENAME }}
      fio_pkg_artifact_id: ${{ steps.artifact-runtime.outputs.artifact-id }}
      fio_pkg_source_filename: ${{ steps.pkg-metadata.outputs.FIO_PKG_SOURCE_FILENAME }}
      fio_pkg_source_artifact_id: ${{ steps.artifact-source.outputs.artifact-id }}
    steps:
      - name: Install latest hipFile dev package
        run: |
          curl -L https://github.com/ROCm/hipFile/releases/download/nightly/hipfile-0.2.0.70200-nightly.9999.el9.x86_64.rpm -o hipfile.rpm
          curl -L https://github.com/ROCm/hipFile/releases/download/nightly/hipfile-devel-0.2.0.70200-nightly.9999.el9.x86_64.rpm -o hipfile-devel.rpm
          dnf install -y ./hipfile.rpm ./hipfile-devel.rpm
      - name: Fetching FIO repository...
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
        with:
          # Need to specify, otherwise uses the wrong ref if calling this workflow
          # from another repo.
          # Need to change to `hipFile` branch.
          repository: ROCm/fio
          ref: rildixon/ci-hook-for-hipfile
          path: ${{ github.workspace }}/fio/fio-src
      - name: Setup rpmbuild environment
        working-directory: ${{ github.workspace }}/fio
        run: |
          mkdir -p rpmbuild/BUILD rpmbuild/RPMS rpmbuild/SOURCES rpmbuild/SPECS rpmbuild/SRPMS
          export FIO_VERSION="$(./fio-src/FIO-VERSION-GEN 2>&1 | sed -E 's|.*fio-([0-9.]+).*|\1|')"
          echo "FIO_VERSION=${FIO_VERSION}" >> "${GITHUB_ENV}"
          tar -cjf ./rpmbuild/SOURCES/fio-${FIO_VERSION}.tar.bz2 \
            --exclude="debian" \
            --exclude="docker" \
            --exclude="rpm" \
            --exclude-vcs \
            --transform="s|^fio-src|fio-${FIO_VERSION}|" \
            fio-src
          cp ./fio-src/rpm/fedora/fio.spec ./rpmbuild/SPECS
      - name: Build FIO with hipFile support
        working-directory: ${{ github.workspace }}/fio/rpmbuild
        # Referencing github.workspace from the shell within a container
        # does not work out very well.
        # Example assuming GitHub hosted CI runner:
        # github.workspace:    /home/runner/work/fio/fio
        # Container workspace: /_w/fio/fio
        # Use `realpath .` to resolve the container path.
        run: |
          rpmbuild \
            -ba \
            --define="_topdir $(realpath .)" \
            --with=hipfile \
            ./SPECS/fio.spec
      - name: Capture package metadata
        id: pkg-metadata
        env:
          _rpm_path: ./RPMS/x86_64
          _srpm_path: ./SRPMS
        working-directory: ${{ github.workspace }}/fio/rpmbuild
        run: |
          shopt -s nullglob
          ls -al ./RPMS/x86_64 ./SRPMS
          FIO_PKG_DEBUG_FILENAME="$(basename ${_rpm_path}/fio-debuginfo-${FIO_VERSION}-[0-9]*.rpm)"
          FIO_PKG_DEBUG_SOURCE_FILENAME="$(basename ${_rpm_path}/fio-debugsource-${FIO_VERSION}-[0-9]*.rpm)"
          FIO_PKG_HIPFILE_ENGINE_FILENAME="$(basename ${_rpm_path}/fio-engine-hipfile-${FIO_VERSION}-[0-9]*.rpm)"
          FIO_PKG_FILENAME="$(basename ${_rpm_path}/fio-${FIO_VERSION}-[0-9]*.rpm)"
          FIO_PKG_SOURCE_FILENAME="$(basename ${_srpm_path}/fio-${FIO_VERSION}-[0-9]*.src.rpm)"

          echo "FIO_PKG_DEBUG_FILENAME=${FIO_PKG_DEBUG_FILENAME}" >> "${GITHUB_OUTPUT}"
          echo "FIO_PKG_DEBUG_SOURCE_FILENAME=${FIO_PKG_DEBUG_SOURCE_FILENAME}" >> "${GITHUB_OUTPUT}"
          echo "FIO_PKG_HIPFILE_ENGINE_FILENAME=${FIO_PKG_HIPFILE_ENGINE_FILENAME}" >> "${GITHUB_OUTPUT}"
          echo "FIO_PKG_FILENAME=${FIO_PKG_FILENAME}" >> "${GITHUB_OUTPUT}"
          echo "FIO_PKG_SOURCE_FILENAME=${FIO_PKG_SOURCE_FILENAME}" >> "${GITHUB_OUTPUT}"
      - name: Print package metadata for debugging
        env:
          _rpm_path: ./RPMS/x86_64
          _srpm_path: ./SRPMS
        working-directory: ${{ github.workspace }}/fio/rpmbuild
        run: |
          echo "Runtime Package:"
          ${{ format('rpm -qpil --requires {0}/{1}', env._rpm_path, steps.pkg-metadata.outputs.FIO_PKG_FILENAME) }}
          echo -e "\n\nDebug Package:"
          ${{ format('rpm -qpil --requires {0}/{1}', env._rpm_path, steps.pkg-metadata.outputs.FIO_PKG_DEBUG_FILENAME) }}
          echo -e "\n\nDebug Source Package:"
          ${{ format('rpm -qpil --requires {0}/{1}', env._rpm_path, steps.pkg-metadata.outputs.FIO_PKG_DEBUG_SOURCE_FILENAME) }}
          echo -e "\n\nhipFile FIO Engine Package:"
          ${{ format('rpm -qpil --requires {0}/{1}', env._rpm_path, steps.pkg-metadata.outputs.FIO_PKG_HIPFILE_ENGINE_FILENAME) }}
          echo -e "\n\nSource Package:"
          ${{ format('rpm -qpil --requires {0}/{1}', env._srpm_path, steps.pkg-metadata.outputs.FIO_PKG_SOURCE_FILENAME) }}
      - name: Upload FIO Runtime Package as an Artifact
        id: artifact-runtime
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f #v6.0.0
        with:
          name: ${{ steps.pkg-metadata.outputs.FIO_PKG_FILENAME }}
          path: ${{ format('{0}/fio/rpmbuild/RPMS/x86_64/{1}', github.workspace, steps.pkg-metadata.outputs.FIO_PKG_FILENAME) }}
          if-no-files-found: error
          retention-days: 1
          compression-level: 0
      - name: Upload FIO Debug Package as an Artifact
        id: artifact-debug
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f #v6.0.0
        with:
          name: ${{ steps.pkg-metadata.outputs.FIO_PKG_DEBUG_FILENAME }}
          path: ${{ format('{0}/fio/rpmbuild/RPMS/x86_64/{1}', github.workspace, steps.pkg-metadata.outputs.FIO_PKG_DEBUG_FILENAME) }}
          if-no-files-found: error
          retention-days: 1
          compression-level: 0
      - name: Upload FIO Debug Source Package as an Artifact
        id: artifact-debug-source
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f #v6.0.0
        with:
          name: ${{ steps.pkg-metadata.outputs.FIO_PKG_DEBUG_SOURCE_FILENAME }}
          path: ${{ format('{0}/fio/rpmbuild/RPMS/x86_64/{1}', github.workspace, steps.pkg-metadata.outputs.FIO_PKG_DEBUG_SOURCE_FILENAME) }}
          if-no-files-found: error
          retention-days: 1
          compression-level: 0
      - name: Upload FIO hipFile IO Engine Package as an Artifact
        id: artifact-hipfile-engine
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f #v6.0.0
        with:
          name: ${{ steps.pkg-metadata.outputs.FIO_PKG_HIPFILE_ENGINE_FILENAME }}
          path: ${{ format('{0}/fio/rpmbuild/RPMS/x86_64/{1}', github.workspace, steps.pkg-metadata.outputs.FIO_PKG_HIPFILE_ENGINE_FILENAME) }}
          if-no-files-found: error
          retention-days: 1
          compression-level: 0
      - name: Upload FIO Source Package as an Artifact
        id: artifact-source
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f #v6.0.0
        with:
          name: ${{ steps.pkg-metadata.outputs.FIO_PKG_SOURCE_FILENAME }}
          path: ${{ format('{0}/fio/rpmbuild/SRPMS/{1}', github.workspace, steps.pkg-metadata.outputs.FIO_PKG_SOURCE_FILENAME) }}
          if-no-files-found: error
          retention-days: 1
          compression-level: 0
